/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Validator.DataValidator;
import Validator.MessageLogin;
import connection.LoadData;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.KhachHang;
import model.NhanVien;
import controller.Controller;
import javax.swing.JOptionPane;
import model.NhanVien1;

/**
 *
 * @author PC
 */
public class GiaoDienSuaThongTin1 extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienSuaThongTin
     */
    public GiaoDienSuaThongTin1() {
        initComponents();
        thongtinNV();
//        KhachHang kh = null;
//        for (KhachHang khh : controller.Controller.arrayListKhachHang) {
//            if(khh.getTenDangNhap().equals(controller.Controller.tk.getTenDangNhap()))
//                kh = khh;
//        }
//        ipname.setText(kh.getTenKhachHang());
//        ipNS.setDate(kh.getNgaySinh());
//        ipSDT.setText(kh.getSDT());
//        ipEmail.setText(kh.getEmail());
//        jTextField3.setText(controller.Controller.tk.getTenDangNhap());
        
        
    }
     private boolean validForm()
    {
        if (!DataValidator.validateIsNumber(ipSDT, "Điện thoại phải là số")) {
            return false;
        }
        if (!DataValidator.validatePhone10(ipSDT, "Số điện thoại phải 10 ký tự")) {
            return false;
        }
        return true;
    }
    public void thongtinNV(){
        NhanVien nv = null;
         if(Controller.tk.getLoaiTaiKhoan().equals("nhân viên")){
             for (NhanVien nvv : controller.Controller.arrayListNhanVien) {
            if(nvv.getTenDangNhap().equals(controller.Controller.tk.getTenDangNhap()))
                nv = nvv;
        }
        ipname.setText(nv.getTenNhanVien());
        ipSDT.setText(nv.getSDT());
        ipTendangnhap.setText(nv.getTenDangNhap());
//        txtLuong.setText(controller.Controller.tk.getTenDangNhap());
        txtLuong.setText(Integer.toString(nv.getLuong()));
         }
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ipname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ipSDT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ipTendangnhap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        baoloiname = new javax.swing.JLabel();
        baoloiSDT = new javax.swing.JLabel();
        baoloimail = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        baoloi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Sửa Thông Tin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(109, 11, 170, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Họ Và Tên");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 59, 15);

        ipname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ipnameMouseClicked(evt);
            }
        });
        getContentPane().add(ipname);
        ipname.setBounds(100, 50, 290, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("SDT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 23, 15);

        ipSDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ipSDTMouseClicked(evt);
            }
        });
        ipSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipSDTActionPerformed(evt);
            }
        });
        getContentPane().add(ipSDT);
        ipSDT.setBounds(100, 90, 290, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tên đăng nhập");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 140, 84, 15);

        ipTendangnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ipTendangnhapMouseClicked(evt);
            }
        });
        getContentPane().add(ipTendangnhap);
        ipTendangnhap.setBounds(100, 130, 290, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Luong");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 180, 50, 15);

        txtLuong.setBackground(new java.awt.Color(204, 204, 204));
        txtLuong.setEnabled(false);
        getContentPane().add(txtLuong);
        txtLuong.setBounds(100, 170, 290, 30);

        jLabel9.setText("<HTML><u></u></HTML>");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(216, 410, 0, 0);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Lưu Thông Tin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 220, 120, 30);

        baoloiname.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(baoloiname);
        baoloiname.setBounds(110, 80, 262, 12);

        baoloiSDT.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(baoloiSDT);
        baoloiSDT.setBounds(240, 120, 150, 10);

        baoloimail.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(baoloimail);
        baoloimail.setBounds(110, 160, 180, 10);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("<HTML><u>Sửa Mật Khẩu</u></HTML>");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12);
        jLabel12.setBounds(170, 260, 100, 17);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 10, 60, 30);

        baoloi.setForeground(new java.awt.Color(51, 0, 255));
        getContentPane().add(baoloi);
        baoloi.setBounds(90, 290, 250, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

//        NhanVien1 nv1 = new NhanVien1(ipSDT.getText(), ipname.getText(), ipTendangnhap.getText());
//          StringBuilder sb = new StringBuilder();
//          DataValidator.validateEmpty(ipname, sb, "Họ và tên không được để trống");
//          DataValidator.validateEmpty(ipSDT, sb, "SĐT không được để trống");
//          DataValidator.validateEmpty(ipTendangnhap, sb, "Tên đăng nhập không được để trống");
//          if(sb.length()>0){
//            MessageLogin.showErrorDangnhap(this, sb.toString(), "Lỗi");
//            return;
//        }
//          if (!validForm()) {
//            return;
//          }
////        System.out.println(kh.getTenKhachHang());
////             connection.UpdateData.updateKhachHang(kh);
//              connection.UpdateData.updateNhanvien1(nv1);
//              JOptionPane.showMessageDialog(null, "Sửa thông tin thành công", "Thông báo", 1);
//              new GiaoDienTimChuyenBay().setVisible(true);
//              this.dispose();
         String str = ipTendangnhap.getText();
         NhanVien1 nv1 = new NhanVien1(ipSDT.getText(), ipname.getText(), ipTendangnhap.getText());
        int a = 0;
        if(ipname.getText().length() == 0){
            baoloiname.setText("Họ Tên không được để trống");
            a++;
        }  
        if(ipSDT.getText().length() == 0){
            baoloimail.setText("SDT không hợp lệ");
            a++;
        } 
        System.out.println(nv1.getTenNhanVien());
        if(a ==0){
//             connection.UpdateData.updateKhachHang(kh);
                connection.UpdateData.updateNhanVien1(nv1);
              new GiaoDienTimChuyenBay().setVisible(true);
              this.dispose();
             baoloi.setText("Sửa thông tin thành công");
        }
           
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ipnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipnameMouseClicked
         baoloiname.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_ipnameMouseClicked

    private void ipSDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipSDTMouseClicked
         baoloiSDT.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_ipSDTMouseClicked

    private void ipTendangnhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipTendangnhapMouseClicked
        baoloimail.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_ipTendangnhapMouseClicked

    private void ipSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipSDTActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
         new GiaoDienQuanLy().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
         new GiaoDienDoiMatKhau().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienSuaThongTin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baoloi;
    private javax.swing.JLabel baoloiSDT;
    private javax.swing.JLabel baoloimail;
    private javax.swing.JLabel baoloiname;
    private javax.swing.JTextField ipSDT;
    private javax.swing.JTextField ipTendangnhap;
    private javax.swing.JTextField ipname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtLuong;
    // End of variables declaration//GEN-END:variables
}
