/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import connection.LoadData;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.ChuyenBay;
import controller.Controller;



/**
 *
 * @author PC
 */
public class GiaoDienQuanLy extends javax.swing.JFrame {

    private DefaultTableModel table;
    private int cheDo;

    /**
     * Creates new form GiaoDienNhanVien
     */
    public GiaoDienQuanLy() {
        initComponents();
        table = (DefaultTableModel) jTable1.getModel();
        cheDo=0;
        showData();
            System.out.println(controller.Controller.tk.getLoaiTaiKhoan());
//        if(controller.Controller.tk.getLoaiTaiKhoan().equals("staff")){
//              btnNhanVien.setEnabled(false);
//        }
        if (Controller.tk.getLoaiTaiKhoan().equals("admin")) {
            jLabel3.setText(Controller.tk.getTenDangNhap());
            jLabel4.setText(controller.Controller.tk.getLoaiTaiKhoan());
//            btnNhanVien.setEnabled(true);
        } else if (Controller.tk.getLoaiTaiKhoan().equals("nhân viên")) {
         //   controller.Controller.tk.setLoaiTaiKhoan("nhân viên");
            jLabel3.setText(Controller.tk.getTenDangNhap());
            jLabel4.setText(controller.Controller.tk.getLoaiTaiKhoan());
            btnNhanVien.setEnabled(false);
            btnThongke.setEnabled(false);
        }
//        if(Controller.tk.getLoaiTaiKhoan().equals("nhân viên")){
//            jLabel16.setEnabled(true);
//        }else{
//            jLabel16.setText("");
//        }  
        //// 
        
    }

        private void showData(){
        
        new LoadData();
        table.setRowCount(0);
        for (ChuyenBay cb: controller.Controller.arrayListChuyenBay) {
           if(cb.getTrangThai()== this.cheDo)
            table.addRow(new Object[]{cb.getMaChuyenBay(),cb.getSHMB(),cb.getDuongBay().getMaSanBayDi()+"->"+cb.getDuongBay().getMasanBayDen(),cb.getNgayBay()+" " +cb.getGioBay()});       
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnChuyenBay = new javax.swing.JButton();
        btnDuongBay = new javax.swing.JButton();
        btnSanBay = new javax.swing.JButton();
        btnMayBay = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnThongke = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldMaCB = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jDateChooserNgayBay = new com.toedter.calendar.JDateChooser();
        jComboBox_GioDi1 = new javax.swing.JComboBox<>();
        jComboBox_PhutDi = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnTimChuyen = new javax.swing.JButton();
        jTextFieldMaCB1 = new javax.swing.JTextField();
        jTextFieldMaCB2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(1070, 1350));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 760));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnChuyenBay.setBackground(new java.awt.Color(0, 153, 153));
        btnChuyenBay.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnChuyenBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kisspng-airplane-flight-computer-icons-airline-ticket-ticket-5abcf231227d01.6528235915223322091413.png"))); // NOI18N
        btnChuyenBay.setText("Chuyến Bay");
        btnChuyenBay.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnChuyenBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenBayActionPerformed(evt);
            }
        });
        jPanel1.add(btnChuyenBay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 334, 85));

        btnDuongBay.setBackground(new java.awt.Color(0, 153, 153));
        btnDuongBay.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnDuongBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/_Pngtree_route_flat_multi_color_icon_3777261-removebg-preview.png"))); // NOI18N
        btnDuongBay.setText("Đường Bay");
        btnDuongBay.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDuongBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuongBayActionPerformed(evt);
            }
        });
        jPanel1.add(btnDuongBay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 334, 85));

        btnSanBay.setBackground(new java.awt.Color(0, 153, 153));
        btnSanBay.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnSanBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_runway_52px.png"))); // NOI18N
        btnSanBay.setText("Sân Bay");
        btnSanBay.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSanBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanBayActionPerformed(evt);
            }
        });
        jPanel1.add(btnSanBay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 334, 85));

        btnMayBay.setBackground(new java.awt.Color(0, 153, 153));
        btnMayBay.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnMayBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image-removebg-preview (1)w.png"))); // NOI18N
        btnMayBay.setText("Máy Bay");
        btnMayBay.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayBayActionPerformed(evt);
            }
        });
        jPanel1.add(btnMayBay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 334, 85));

        btnNhanVien.setBackground(new java.awt.Color(0, 153, 153));
        btnNhanVien.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/—Pngtree—employee icon vector illustration in_4257910.png"))); // NOI18N
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.setDoubleBuffered(true);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        jPanel1.add(btnNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 334, 85));

        btnThongke.setBackground(new java.awt.Color(0, 153, 153));
        btnThongke.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/monye.png"))); // NOI18N
        btnThongke.setText("Thống Kê");
        btnThongke.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeActionPerformed(evt);
            }
        });
        jPanel1.add(btnThongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 810, 334, 85));

        btnThoat.setBackground(new java.awt.Color(0, 153, 153));
        btnThoat.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/56805.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 910, 334, 85));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("________________________________________");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 330, 20));
        jLabel1.getAccessibleContext().setAccessibleName("________________________________________________");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/animation.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 278, 170));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("tên");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 330, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("phân quyền");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 245, 330, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Đổi mật khẩu");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("Đăng xuất");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel15.setText("/");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 10, 10, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Chuyến Bay", "SHMB", "Đường Bay", "Thời Gian"
            }
        ));
        jTable1.setRowHeight(34);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel8.setBackground(new java.awt.Color(0, 204, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CHUYẾN BAY NGÀY HÔM NAY ");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("SHMB");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Giờ Bay");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Mã Chuyến Bay");

        jTextFieldMaCB.setEnabled(false);
        jTextFieldMaCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldMaCBMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Ngày Bay");

        jDateChooserNgayBay.setDateFormatString("dd/MM/yyyy");
        jDateChooserNgayBay.setEnabled(false);
        jDateChooserNgayBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooserNgayBayMouseClicked(evt);
            }
        });

        jComboBox_GioDi1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jComboBox_GioDi1.setEnabled(false);

        jComboBox_PhutDi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "" }));
        jComboBox_PhutDi.setEnabled(false);
        jComboBox_PhutDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PhutDiActionPerformed(evt);
            }
        });

        jLabel13.setText(":");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Đường Bay");

        btnTimChuyen.setBackground(new java.awt.Color(255, 255, 102));
        btnTimChuyen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTimChuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7d74215fae51a37bb027798dedc16812-removebg-preview.png"))); // NOI18N
        btnTimChuyen.setText("Tìm Vé");
        btnTimChuyen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTimChuyen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTimChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimChuyenActionPerformed(evt);
            }
        });

        jTextFieldMaCB1.setEnabled(false);
        jTextFieldMaCB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldMaCB1MouseClicked(evt);
            }
        });
        jTextFieldMaCB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMaCB1ActionPerformed(evt);
            }
        });

        jTextFieldMaCB2.setEnabled(false);
        jTextFieldMaCB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldMaCB2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMaCB2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooserNgayBay, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jComboBox_GioDi1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox_PhutDi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(btnTimChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldMaCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(249, 249, 249))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMaCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(btnTimChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMaCB2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserNgayBay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox_GioDi1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_PhutDi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        new GiaoDienNhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnDuongBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuongBayActionPerformed
        // TODO add your handling code here:
         new GiaoDienDuongBay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDuongBayActionPerformed

    private void btnSanBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanBayActionPerformed
        // TODO add your handling code here:
        new GiaoDienSanBay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSanBayActionPerformed

    private void btnChuyenBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenBayActionPerformed
        // TODO add your handling code here:
         new GiaoDienChuyenBay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnChuyenBayActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayBayActionPerformed
        // TODO add your handling code here:
        new GiaoDienMayBay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMayBayActionPerformed

    private void btnTimChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimChuyenActionPerformed
        
        new GiaoDienTimChuyenBay().setVisible(true);
           this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimChuyenActionPerformed

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        new DangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeActionPerformed
        // TODO add your handling code here:
        new GiaoDienThongKe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThongkeActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new GiaoDienDoiMatKhau().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new DangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked



//
    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        int row= jTable1.getSelectedRow();
        jTextFieldMaCB1.setText((String) jTable1.getValueAt(row,0));
                jTextFieldMaCB.setText((String) jTable1.getValueAt(row,1));
        jTextFieldMaCB2.setText((String) jTable1.getValueAt(row,2));

        String datebay = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
        jComboBox_GioDi1.setSelectedItem(datebay.substring(11, 13));   
        jComboBox_PhutDi.setSelectedItem(datebay.substring(14, 16));
        
        
         datebay=datebay.substring(8,10)+"/"+datebay.substring(5,7)+"/"+datebay.substring(0,4);
     
         try {
            java.util.Date  datetmp = new SimpleDateFormat("dd/MM/yyyy").parse(datebay);
             jDateChooserNgayBay.setDate(datetmp);
         } catch (ParseException ex) {
             Logger.getLogger(GiaoDienChuyenBay.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jTable1MousePressed

    private void jTextFieldMaCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMaCBMouseClicked
    }//GEN-LAST:event_jTextFieldMaCBMouseClicked

    private void jDateChooserNgayBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooserNgayBayMouseClicked
    }//GEN-LAST:event_jDateChooserNgayBayMouseClicked

    private void jComboBox_PhutDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PhutDiActionPerformed
    }//GEN-LAST:event_jComboBox_PhutDiActionPerformed

    private void jTextFieldMaCB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMaCB1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaCB1MouseClicked

    private void jTextFieldMaCB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMaCB2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaCB2MouseClicked

    private void jTextFieldMaCB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMaCB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMaCB1ActionPerformed

    

    
  
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenBay;
    private javax.swing.JButton btnDuongBay;
    private javax.swing.JButton btnMayBay;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSanBay;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThongke;
    private javax.swing.JButton btnTimChuyen;
    private javax.swing.JComboBox<String> jComboBox_GioDi1;
    private javax.swing.JComboBox<String> jComboBox_PhutDi;
    private com.toedter.calendar.JDateChooser jDateChooserNgayBay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldMaCB;
    private javax.swing.JTextField jTextFieldMaCB1;
    private javax.swing.JTextField jTextFieldMaCB2;
    // End of variables declaration//GEN-END:variables
}
